### ISSUE TITLE
Add drag to select support

### ISSUE THREAD

**Issue by Eddie-CooRo** [Kiarash-Z/react-persian-calendar-date-picker#1]
Hi, thank you for this great library.
I took a look at it and I thought it would be nicer for this library if it supports drag to select feature out of the box.
So I tweaked its code for one or two hours and here is what I achieved so far:
![](https://media.giphy.com/media/ciwXHWdfJS6kHZ5cJY/giphy.gif)

I wonder if It's ok to open a pull request for this.

**Comment by Kiarash-Z** [comment]
HI Eddie, 
Feel free to submit a pull request. Any great contribution like this will be highly appreciated 😊

**Comment by Kiarash-Z** [comment]
For the sake of contribution, I pushed a new branch called 'develop'. You can work on that branch.
New "Contribution" section will be added soon to the site.
