### ISSUE TITLE
Proprietary fonts used in playground

### ISSUE THREAD

**Issue by par6n** [Kiarash-Z/react-persian-calendar-date-picker#12]
There is a proprietary font used in the playground which can cause troubles. How about [Shabnam](http://rastikerdar.github.io/shabnam-font/)?

**Comment by Kiarash-Z** [comment]
Hi @par6n and thanks for reaching out. I've bought the license for the font, but I'm quite ambivalent whether I'm using the .current license plan or not. I gotta ask Moslem Ebrahimi for it.

**Comment by Kiarash-Z** [comment]
I asked Mr.Ebrahimi, and the project is using the appropriate license plan now 🎉
