### ISSUE TITLE
The Datepicker is extremely slow

### ISSUE THREAD

**Issue by ahmadi3d** [Kiarash-Z/react-persian-calendar-date-picker#13]
I tried using this datepicker and i liked everything about it the only problem is that its extremely slow, meaning the window for pick the date lags and it has low FPS
"react": "^16.8.6",

```
import "react-persian-calendar-date-picker/lib/DatePicker.css";
import DatePicker from "react-persian-calendar-date-picker";

<DatePicker
    selectedDay={null}
    onChange={null}
    inputPlaceholder="انتخاب روز"
/>
```

**Comment by Kiarash-Z** [comment]
Hi, @ahmadi3d can you provide an example in [Codesandbox](https://codesandbox.io)? As far as I've tested it's completely 60fps.

**Comment by ahmadi3d** [comment]
Hi, @Kiarash-Z , I managed to find the reason for this issue, this bug (low fps and lag) happens when instead of using hook, you simply call the component inside a class component, i don't know why this happens but i managed to fix it after using react hooks similar to the examples in the documentation

**Comment by Kiarash-Z** [comment]
It shouldn't make a difference:/ feel free to reach out if the issue appears again❤️
