### ISSUE TITLE
DatePicker's calendar falls behind other panels

### ISSUE THREAD

**Issue by ahmadi3d** [Kiarash-Z/react-persian-calendar-date-picker#16]
Hello
I am using `material UI`, i use `Cards` as panels to style my pages, today i tried implanting the `DatePicker` but it seems that when i open the calendar it falls behind the other panels and even the elements inside the same panel (`<Card>`)
Here is an image : 
https://ibb.co/842DZjq

I tried giving the `DatePicker` and the `calendarClassName `style, in which i changed the `z-index` and position, but none of them work and the calendar still doesn't open in the front
Can you help me solve this issue ?, is there some kind of property that i don't know about ?
Thanks!

**Comment by Kiarash-Z** [comment]
Hello, Have you tried using `wrapperClassName `  instead of `calendarClassName`? you can try it. if it doesn't work, you can try wrapping the whole `<DatePicker />` component in a `div` tag as:
```
<div style={{ position: 'relative', zIndex: '100' }}>
  <DatePicker
    ...someProps
   />
</div>
```

**Comment by ahmadi3d** [comment]
Good news!, Using the wrapperClassName solved the issue of fall behind the elements in the same div (Card), but the calendar is still behind the other panels: 
https://ibb.co/CK1TfMN
I also tried using a div but it didn't solve the problem.

**Comment by ahmadi3d** [comment]
I just tried the default DatePicker in material UI and react and they both seem to work fine! 
here is an image : 
https://ibb.co/GRYGR6q
the code for the datepicker: 
```
import TextField from '@material-ui/core/TextField';
<TextField
        id="date"
        label="Birthday"
        type="date"
        defaultValue="2017-05-24"
        className={classes.textField}
        InputLabelProps={{
          shrink: true,
        }}
/>
```

I think its worth while to take a look at the css file of these date pickers and see how they are made so they can float above everything without any problem,
I am trying to do the same but i am not that experienced with using css

**Comment by Kiarash-Z** [comment]
I can give a `z-index` of 1000 and it would float above everything, but that's not a consistent nor an appropriate way to do so. If you demonstrate a demo on [Codesandbox](https://codesandbox.io/) with similar Material UI components, I can take a look and tell you the best way to resolve the issue.

**Comment by ahmadi3d** [comment]
Here you go, this is an example of what i was talking about
https://codesandbox.io/s/objective-meadow-ergj0?fontsize=14

**Comment by Kiarash-Z** [comment]
Got it! It's not actually because of `z-index`. Thus, It's because of Material-UI Paper component styles. Paper component has an `overflow: hidden` style, and by removing it, everything works just fine:

![image](https://user-images.githubusercontent.com/20098648/61608758-2abbb900-ac69-11e9-9f6a-904efa143bfd.png)

**Comment by ahmadi3d** [comment]
Yes, before posing this issue i also did found out that by changing the overflow's state, the `DatePicker` works but because changing it would break the style of `Material UI` i did not pursue it any further.  
I have start a question in `Stackoverflow` :  
https://stackoverflow.com/questions/57134622/my-datepickers-calendar-opens-behind-the-card-component/57135443?noredirect=1#comment100789145_57135443
Which resulted in an answer that by changing the `CSS` of your component it is able to fix the issue of calendar hiding behind the panels, but to this moment this answer also causes the functionality of the calendar to breaks, which i think should be fixable and i have asked the person who has answered to fix this issue (or maybe wait for someone else to offer a better solution)
Here is the final outcome of the answer in `Stackoverflow` which fixes the current issue but breaks the functionality: 
https://codesandbox.io/s/elastic-franklin-qcde4?fontsize=14
I hope that maybe this can give you some idea about a better solution ?
Thanks!

**Comment by ahmadi3d** [comment]
A very good answer seems to have appeared on the `stackoverflow`, it seems originally to avoid such complications you should used [Portal ](https://reactjs.org/docs/portals.html)to implant the component, after reading on portal it seems exactly what a calendar should be, here is a sentence which copied from its documentation : 
"A typical use case for portals is when a parent component has an overflow: hidden or z-index style, but you need the child to visually “break out” of its container. For example, dialogs, hovercards, and tooltips."

As you can see i think that its worth while taking your wonderful `DatePicker`(one of the best for react), to portal which not only solves the problem `with Material UI`, but also other frame works!
Thanks for the hard work.
Good luck.

**Comment by Kiarash-Z** [comment]
A good case for portals is when you want to open the date picker "outside" of the child itself like in a modal, but when you want to render it directly into a child, it's not the case. take a look at the `portal` version of this famous React date picker: [It opens like a modal](https://reactdatepicker.com/#example-32)

**Comment by ahmadi3d** [comment]
I see, so you are saying using Portal will result in a modal like opening, but still i think its not a bad option to have, in the component you linked the user can enable Portal mode using "withPortal", is it possible to add this option to the DatePicker, this way at least in cases like mine, this can work as an alternative solution.

**Comment by Kiarash-Z** [comment]
Thanks for the suggestion. In fact, this component is highly flexible. you can use any modal you like and include the picker into it as I myself did in a project. Still, I think it's a good idea to integrate a built-in modal for it👍

**Comment by Kiarash-Z** [comment]
Yet, I wonder how [this](https://ibb.co/GRYGR6q) works. Can you provide an example of this one on Codesandbox as well?

**Comment by Kiarash-Z** [comment]
This issue got closed because of inactivity. Feel free to open it when you're there😇

**Comment by me82852578** [comment]
This is my solution, maybe not the best, but at least I have been running well in my project for a while .
[solution](https://stackoverflow.com/questions/64458075/react-modern-calendar-datepicker-overlaps-with-datepicker-inputs-below/65579662#65579662)

**Comment by filippozanfini** [comment]
Any news about this?

**Comment by ahmadi3d** [comment]
> Any news about this?

I did fix the issue myself but I have forgot what I did, But I think I applied custom styling to it, what I can tell you is that I switched to "@mui/x-date-pickers" for my new projects and I never had a problem with it, considering the current library is inactive I suggest you to do the same.
