### ISSUE TITLE
how to use it without useState

### ISSUE THREAD

**Issue by elyasmotazedy** [Kiarash-Z/react-persian-calendar-date-picker#20]
i have class component and i have state 
i dont wanna use like this :
const [selectedDay, setSelectedDay] = useState(null);

how can i change  it for class component 
thanks

**Comment by Kiarash-Z** [comment]
Hello Elyas, 

I highly encourage you to use new React hooks API, but if you want a class-based example, [I made one on CodeSandbox](https://codesandbox.io/s/jovial-moore-h186k)
