### ISSUE TITLE
support multi select(API suggestions?)

### ISSUE THREAD

**Issue by mohammadsaleh** [Kiarash-Z/react-persian-calendar-date-picker#21]
Hi,
dose it support multi select date by click?!

**Comment by thebrodmann** [comment]
Related to #11

**Comment by Kiarash-Z** [comment]
Hi @mohammadsaleh,

This feature will be implemented soon in 1.2.0. I will be working on it 😊

**Comment by Kiarash-Z** [comment]
@thebrodmann @mohammadsaleh I'm thinking of a great API for this feature. For now, we only have 2 main types of date picker:
- Single-day selection
- Range day selection
It's noteworthy that they're distinguished by `isDayRange ` prop. By implementing multi selection, there will be a 3rd type.  Any suggestion is welcome! maybe we would have something like a new prop e.g `isMultiSelectable` (and the type change for the `selectedDay` and `selectedDayRange` props). Or, we can simply support `Array` type for these two. Any other idea? 💡 🤔

**Comment by thebrodmann** [comment]
I put my proposal for API change in #22 because it was somewhere between this issue and new issue so I just preferred to open a new issue for that.

**Comment by mohammadsaleh** [comment]
> Hi @mohammadsaleh,
> 
> This feature will be implemented soon in 1.2.0. I will be working on it 😊

Thanks ;)

**Comment by Kiarash-Z** [comment]
Moved to #22
