### ISSUE TITLE
react-native 

### ISSUE THREAD

**Issue by sajjad7622** [Kiarash-Z/react-persian-calendar-date-picker#25]
hi ! can i  use this on my react-native project ?

**Comment by thebrodmann** [comment]
Hey @sajjad7622, Unfortunately, it's not possible yet as the components return HTML VDOM.
BTW, for now if you wanna use this library in React Native, you can fork the repo and adapt it to work with React Native.

@Kiarash-Z Is there any roadmap for React Native?

**Comment by Kiarash-Z** [comment]
Hi,
Currently, I don't have any plan for React Native version. But, a friend of mine is working on a similar module for React Native.

**Comment by Kiarash-Z** [comment]
@sajjad7622 you can include this by [using WebView ](https://facebook.github.io/react-native/docs/webview), but it's not recommenced

**Comment by hiradary** [comment]
@sajjad7622 Check this out :
https://github.com/HosseinShabani/react-native-modern-datepicker
