### ISSUE TITLE
add ability to pick custom year and month 

### ISSUE THREAD

**Issue by simti** [Kiarash-Z/react-persian-calendar-date-picker#3]
Hi,thanks for this library.
I think one feature this library needs is the ability to select particular year or month without sliding.
something like this for example:
![image](https://user-images.githubusercontent.com/13396356/57327205-93dc6780-7123-11e9-8fe9-8d27026fa2b8.png)

**Comment by Kiarash-Z** [comment]
@simti this feature has been added in #10. You can use it now!😊
