### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by judsonjuniorr** [Kiarash-Z/react-persian-calendar-date-picker#32]
Hello,

Any plans on making a locale option?

Thanks.

**Comment by Kiarash-Z** [comment]
Hello,

Do you mean supporting Gregorian calendar?

**Comment by judsonjuniorr** [comment]
Yes, and the locale for weeks, months...

**Comment by Kiarash-Z** [comment]
Yeah, I'm working on it!😊I will deprecate this package (because it includes "Persian" word), and Publish a new one including Gregorian translations

**Comment by Kiarash-Z** [comment]
Moved to #22
