### ISSUE TITLE
support allowDisabledDaysRange flag

### ISSUE THREAD

**Issue by jafar-rezaei** [Kiarash-Z/react-persian-calendar-date-picker#33]
Hi ,
Thanks Kia to this great work.

Some times we may need to select disabled days on a range.
for example :
If we want to get pool ticket for a range, and odd days of week are for `female` we should allow male user to select a range of dates that only contain select-able days.

**Comment by thebrodmann** [comment]
What about sending a function to determine a day should be disabled or not?

```jsx
<DatePicker disabledDays={isEvenDay} />
```

**Comment by jafar-rezaei** [comment]
@thebrodmann , thanks .
Actually, I was thinking of getting only selected days , instead of period of dates as string.
imagine we have some kind of disabled days , without any formula ...

**Comment by thebrodmann** [comment]
I didn't get your use case! Can you provide an example?

**Comment by thebrodmann** [comment]
>‌ to select a range of dates that only contain select-able days.

So you wanna send a white-list to the component? Also in that way sending a function can help:

```jsx
const selectableDays = [1,2,3]

<DatePicker disabledDays={({ day }) => !selectableDays.include(day)}>
```

Does the above API solve your case?

**Comment by jafar-rezaei** [comment]
@thebrodmann thanks to your great example. yeah it will so useful , but my main problem was with range select returned value. Which just tells us about `startDate` till `endDate` , if we want to add a flag to allow user to choose `range` even with disabled days .. we should make another way to hold really chose days.
I mean, we should set value for days , beside of setting startDate and endDate. Maybe you ask 

> Why do not store startDate till endDate, and calculate every thing we want from that ?

if we get disabled days from `api` and user select a range of dates , and pay for it , then some day our api data changed and , disabled days info changed ... the payment of user will be invalid.
thats why we should store real chose days  ... 

I forke the repo and did some work around , maybe it could be a good PR

**Comment by jafar-rezaei** [comment]
#34 https://github.com/Kiarash-Z/react-persian-calendar-date-picker/pull/34

**Comment by thebrodmann** [comment]
I got it.
It's a miss-behavior if a range calendar returns multiple days!
If you wanna get multiple days from the calendar so you need to use multiple-day selection mode that has been proposed in #22 (It's not available yet).

**Comment by Kiarash-Z** [comment]
Hi @jafar-rezaei, sry for latency in responding to this issue. Now, the problem is with the current state of the date picker, we can't include a disabled day in `disabledDays` prop. Am I right?

**Comment by jafar-rezaei** [comment]
@Kiarash-Z , passing function to `disabledDays` is a good option , but my problem was some kind of multi days selection and allowing user to choose a range , that has disabled days and got selected range days. Last night I worked a bit and make PR which solved this for me.

**Comment by Kiarash-Z** [comment]
@jafar-rezaei Unless I understand your case completely, I can't review your PR. If it's a really special case and it just happens for you, you can install your own fork and work with it. Otherwise, I need a clear description of what is the case and why would you need such prop❤️

**Comment by thebrodmann** [comment]
> but my problem was some kind of multi days selection and allowing user to choose a range

If you wanna the appearance of range selection, the value should be a range. So it's on your shoulder to convert a range to multiple days with filtering disabled days.

The following example is only for demonstration purpose so it just gives you the idea:
```jsx
const [range, setRange] = useState({ from: undefined, to: undefined })
const disabledDays = [{ day: 1 }, { day: 2 }, { day: 3 }]
const totalDays = getAllDaysFromRange(range, disabledDays) // Your converted data

<Calendar value={range} onChange={setRange} disabledDays={disabledDays} />
```

**Comment by jafar-rezaei** [comment]
@Kiarash-Z actually yeah, it is some special necessity of our app ❤️
@thebrodmann thanks to good example 👍 , but still need that flag to enable period choose .

thanks , it is handled in my fork and problem solved.
