### ISSUE TITLE
Day Item Layout

### ISSUE THREAD

**Issue by Aryan-mor** [Kiarash-Z/react-persian-calendar-date-picker#37]
Is it possible to change day item's layout .

**Comment by Kiarash-Z** [comment]
Hello Aryan,
what do you mean by "day item's layout"? can you explain it more explicitly please?

**Comment by Aryan-mor** [comment]
Days layout customize, like this =>
![Before Customized](https://user-images.githubusercontent.com/22844436/66292213-9fa9a100-e8f0-11e9-947a-65baa06366e0.png)
![[After Customized](https://user-images.githubusercontent.com/22844436/66292214-a0423780-e8f0-11e9-992d-09c528511d98.jpg)

**Comment by Kiarash-Z** [comment]
This is not possible yet, but I consider adding a `renderDayItem` prop for such purposes in the next version 👍

**Comment by Kiarash-Z** [comment]
Moved to #22
