### ISSUE TITLE
can i use datepicker in formal class ?

### ISSUE THREAD

**Issue by mahyalpr** [Kiarash-Z/react-persian-calendar-date-picker#38]
i want to use this datepicker inside the class and dont want to use useSet().
what is the syntax for using this datepicker?

**Comment by sharifiniaa** [comment]
> i want to use this datepicker inside the class and dont want to use useSet().
> what is the syntax for using this datepicker?

`import React, {Component} from 'react';

import 'react-persian-calendar-date-picker/lib/DatePicker.css';
import DatePicker from 'react-persian-calendar-date-picker';

class UseInClass extends Component {
    constructor(props){
        super(props);
        this.state = {
            selectedDay: null
        }
    }

    setSelectedDay = (data) => {
        this.setState({selectedDay: data})
    };

    render() {
        const {selectedDay} = this.state;
        return(
            <DatePicker
                        selectedDay={selectedDay}
                        onChange={setSelectedDay}
                        inputPlaceholder="انتخاب روز"
                    />
        )
    }

};


export default UseInClass;`

**Comment by Kiarash-Z** [comment]
@mahyalpr Yes, you can. duplication #20 :
[demo on CodeSandBox](https://codesandbox.io/s/jovial-moore-h186k)

**Comment by mahyalpr** [comment]
what about range datepicker?
how to handle from and to ?

**Comment by mahyalpr** [comment]
i fixed the problem:
import React from 'react';
import "react-persian-calendar-date-picker/lib/DatePicker.css";
import DatePicker from "react-persian-calendar-date-picker";


class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedDayRange:{from: null,
        to: null}
    };
    this.handleDatePickerChange=this.handleDatePickerChange.bind(this)
  }
 handleDatePickerChange(newValue){
  this.setState({selectedDayRange:{from:newValue.from,to:newValue.to} });
 }


  render() {

    return (

      <div className="App">
        <DatePicker
        selectedDayRange={this.state.selectedDayRange}
        onChange={this.handleDatePickerChange}
        inputPlaceholder="انتخاب روزهای نمایش"
        isDayRange
      />
      </div>
    );
  }
}

**Comment by Kiarash-Z** [comment]
@mahyalpr I'm Glad you've fixed it. I'm gonna close this issue then 😇

**Comment by thebrodmann** [comment]
@Kiarash-Z I remember another issue with has a similar problem. Should we add this to documentation?
