### ISSUE TITLE
tab problem

### ISSUE THREAD

**Issue by sharifiniaa** [Kiarash-Z/react-persian-calendar-date-picker#39]
Hi
While I’m using the date picker in a form, and press tab to change inputs, suddenly the date picker crashes and its style misaligns; consequently it doesn’t work anymore!
Do you have any possible solution for this?!
![Capture](https://user-images.githubusercontent.com/45081278/66466878-4d9f8180-ea90-11e9-96f6-0a659c4a18e3.JPG)

**Comment by Kiarash-Z** [comment]
Hello Hossein,
Can you provide a gif/video of the problem, please? I can investigate the problem better then.

**Comment by sharifiniaa** [comment]
> Hello Hossein,
> Can you provide a gif/video of the problem, please? I can investigate the problem better then.

I use the Formik for validation and the date picker pass a props children to formik !
![ezgif-2-6b01b5605392](https://user-images.githubusercontent.com/45081278/66471822-e508d280-ea98-11e9-97d0-6e395f2ecab6.gif)

**Comment by Kiarash-Z** [comment]
I tried it with a simple `form` element and found no issue. Can you reproduce this form(only UI) in [CodeSandbox](https://codesandbox.io/) so I can inspect and find the problem?

**Comment by sharifiniaa** [comment]
> 
> 
> I tried it with a simple `form` element and found no issue. Can you reproduce this form(only UI) in [CodeSandbox](https://codesandbox.io/) so I can inspect and find the problem?

you can see the example in this link 
[https://codesandbox.io/embed/practical-bassi-odse8](url)

**Comment by Kiarash-Z** [comment]
@sharifiniaa this is now fixed in v1.1.6. Try the latest version please❤️
