### ISSUE TITLE
add max/min date 

### ISSUE THREAD

**Issue by electather** [Kiarash-Z/react-persian-calendar-date-picker#8]
thanks for the great library. i think it would be great if a native option for setting max/min date was added to this library. there are many use cases e.g. setting birthday or reserving a date. just removing the user's access to those dates is a much better solution (than my current solution of) showing an error to user.

**Comment by Kiarash-Z** [comment]
Hello, thanks for reaching out😊
You can actually do this by providing an array of the disabled days: [disabled days](https://kiarash-z.github.io/react-persian-calendar-date-picker/docs/disabled-days)

**Comment by Kiarash-Z** [comment]
Oh just figured it out. You can't provide an unlimited list of the disabled days. I got to add this feature. Thanks for your great suggestion❤️. I will add it in later versions. (1.1.0 perhaps...)

**Comment by Kiarash-Z** [comment]
@electather this feature has been added in #10. You can use it now!😊
